### PR TITLE
Implement MSelectionList

### PR DESCRIPTION
**Pull request by yantor3d**
### Added
 - Add full stub for `MSelectionList`
   - Implement `__len__`, `.isEmpty()`
   - Implement `.getDependNode`
   - Implement `.getDagPath`
   - Implement `.getPlug`
   - Implement `.getSelectionStrings`
 - Add full stub for `MPlug` 

### Fixed
 - Fix bugs in parse_header script
   - Support multi-line statements
   - Ignore trailing comments
   - Skip "No Script Support" blocks

### wat 
 - MSelectionList::getPlug returns an OK status for a node. You have to check if the attribute is null.

### Notes
 - We should implement a C++ style guide.
 - We should implement MString <-> std::string helper functions
 - We should implement M[T]Array <-> std::vector<T> helper functions

### CODE REVIEW

**Comment by mottosso** [comment]
Great work!

> We should implement a C++ style guide.

Can you elaborate? What would such a style look like, and who would it be for?

> We should implement MString <-> std::string helper functions
> We should implement M[T]Array <-> std::vector helper functions

What kind of helper functions?

**Comment by yantor3d** [comment]
For the style guide... just conventions for how to handle things like:
 - Enum classes (excluding MFn::Type)
 - Which exception to use when (so that everything is not a RuntimeError)
    - Can we define custom exceptions?
 - Curly braces 
 
 For the helper functions...
  - For MString <-> std::string I don't actually know. 
  - For M[T]Array <-> std::vector<T>, functions to convert between the two. See `SelectionList.getSelectionStrings` for an example. Since the M[T]Array objects do not have a common base class, I think one would have to write a separate function for each conversion, unless there's some arcane template magic I am unaware of.

**Comment by mottosso** [comment]
> Which exception to use when (so that everything is not a RuntimeError)
> Can we define custom exceptions?

Good question. I glanced at the native C++ exceptions and there aren't many to choose from. I think it'd make sense to raise our own, but it'd depend on what errors we actually encounter. I'd imagine time and experience could lead the way here. For the time being I'm quite happy making it all runtime errors rather than to try and predict what we might want in the future. Unless it's obvious, like index errors or key errors etc.

A style guide is probably too early. We'd have to speculate a little too much about what might become a problem. I'd imagine we could make note of things that stand out in the README.md for now. What do you think?

> For MString <-> std::string I don't actually know.

Hah. But what made you point it out in the first place? :D

> For M[T]Array <-> std::vector

Ah, yes good point. Let's do what you just did, convert it into a native Python list. I'd imagine we could make a simple helper function to deal with them since these are quite common. Maybe a template, but at the very least just an inline function if performance really was a concern.

On the other hand, generators is another appealing option. Especially if the lists are long, and computing them is expensive.

**Comment by mottosso** [comment]
Would you mind if we used `nose` instead of `pytest`? I'm setting up automated testing with GitHub Actions next.

**Comment by yantor3d** [comment]
I'm fine using `nose`.

I suggested the `MString <-> std::string` interop functions because I had to bounce back and forth between the two a few times and it's clunky. 

I know there is a blog post out there somewhere about replacing or wrapping M[T]Arrays with stdlib components. I'll try to dig it up - I think it did some pointer trickery to traverse the Maya array types...

**Comment by mottosso** [comment]
> I suggested the MString <-> std::string interop functions because I had to bounce back and forth between the two a few times and it's clunky.

Oh I see. Ok, interesting. Well, next time you do, do document it so we can have a nice old look. I imagine it'd be..

- `std::string(myMString.asChar())` and then back again as..
- `MString(myString.c_str())`

> I know there is a blog post out there somewhere about replacing or wrapping M[T]Arrays with stdlib components. I'll try to dig it up - I think it did some pointer trickery to traverse the Maya array types...

In 2019 and above, they've added the means of calling `for (auto& el : mayaArray) {}`, which I *think* should translate natively via pybind11 to native Python types. I'd imagine we could implement similar means for the missing types of 2018.

I do believe it comes down to this addition here: https://help.autodesk.com/view/MAYAUL/2020/ENU/?guid=__cpp_ref_class_m_point_array_html#a5d852fe292e05aaca41615209679fde6

**Comment by yantor3d** [comment]
Will do.

GitHub says there are merge conflicts that can't be resolved in the web app. Do I need to pull from upstream to resolve the conflicts, or is this something you have to do?

**Comment by mottosso** [comment]
You'll need to merge or rebase the changes from here into your local copy.

**Comment by mottosso** [comment]
There's something not right on Linux at the moment, have a look at the `Details` on any of the builds. If you're on Windows (like me) you can build locally on Linux using the Dockerfile included in the repo.

I've added an example to the README on how to do that.

- https://github.com/mottosso/cmdc#build

**Comment by yantor3d** [comment]
Yep, I got the error e-mail last night. I'll look into it after work.

**Comment by yantor3d** [comment]
The code builds on Linux now, and I replaced the `pytest` usages with `nose`.

...please tell me we can squash the commits from this branch.

**Comment by mottosso** [comment]
> ...please tell me we can squash the commits from this branch.

:D If you'd like. Let's do it!

**Comment by yantor3d** [comment]
Thanks, Marcus! I prefer squashed merges because it keeps the mainline neat and tidy :)

**Comment by mottosso** [comment]
Yeah, but we gotta work on getting that high-score too! xD The repo with the most commits wins!

image

**Pull request merged**
