### PR TITLE
Implement DGModifier

### PR DESCRIPTION
**Pull request by yantor3d**
### Added
 - Add MDGModifier bindings

### Changed
 - Add support for `OPENMAYA_PRIVATE` namespace in `parse_headers.py`
   - This always appears at the end of the header, so it stops the iterator early.

Please squash the branch when it is merged.

### CODE REVIEW

**Comment by mottosso** [comment]
There are two things I'm interested in making part of the modifiers in Maya, but aren't sure whether they should be "mixed in" with the vanilla bindings we're making, or whether they should be a separate library, e.g. `cmdc.util`.

```py
import cmdc
from maya import cmds

with cmdc.DGModifier(undoable=True) as mod:
  mod.createNode("...")

cmds.undo()
```

Namely, a native **context manager** and **undo** for anything happening within that context.

Working with [cmdx](https://github.com/mottosso/cmdx) I've found these to be essential to a pleasant experience. Very few operations with the API is useful unless they can be undone, and the modifiers are very good at providing most of the complexity necessary behind making that possible.

It'd look something like this.

- [Example 1](https://github.com/mottosso/ragdoll/blob/b6f0eb82237ac3b18cdb5705ee186301e5d9c419/ragdoll/commands.py#L139)

Where many of the functions take a modifier as argument, so as to continue appending operations onto the future undo stack, and also highlights another convenience aspect I'd like to explore namely the `attribute["access"]`.

Or like this.

- [Example 2](https://github.com/mottosso/ragdoll/blob/b6f0eb82237ac3b18cdb5705ee186301e5d9c419/ragdoll/commands.py#L2009)

Which includes a convenience interface for creating and adding attributes.

On the one hand, it would make the API more useful and less frightening. I think the number one thing scaring developers away from Maya Python API 1.0 and 2.0 is that you must implement undo yourself, and it is far from trivial. On the other hand, it would move cmdc away from just a pure C++ binding. It would make it subjective; how should it work? How should it look? A separate library would solve that, as it could be ignored for anyone not interested in anything but the raw API. But would duplicate a lot of the implementations and increase maintenance cost overall.

So I'd be interested in opinions here, also ping @Muream. What do you guys think?

**Comment by Muream** [comment]
I really like the idea of the DGModifier as a context manager. I also see nothing wrong in having that as part of the `cmdc` binding if that's possible as long as we don't remove anything from the API and just have as an added feature.

I'm generally fine with opinonated decisions as long as they're consistent and are there to make the API more pleasant to work with.
Cmdc already diverges with the API with a couple of things like methods always returning values, proper python sequences, etc.
Having the DGModifier as a context manager goes in the same direction as these decisions to me.

If we do go for a separate `cmdc.util` package, I think I would prefer for its content to be re-exported in `cmdc` so that users just need to import `cmdc`.
Otherwise the features meant to help users get hidden away and are hard to discover

I'm thinking a package structure like this would be good as it would let people just use `cmdc.bindings` if they really wanted to.
```
cmdc/
├── __init__.py  # this would export the content of `bindings` and `util`
├── bindings.py  # currently named cmdc.py
└── util.py
```

As for the `node["attr"]` thing, I like the idea of easy access of the attributes but I don't think I like the syntax. I imagine it's to avoid unreachable attributes that have same name as some methods when implementing `__getattr__`?

**Comment by yantor3d** [comment]
I agree we should make `cmdc` more Pythonic where it makes sense, and making the  DG/DAG Modifier a context makes perfect sense, since it handles adding the block to the undo queue. 

Can DGModifier as a context handle the user calling .doIt() multiple times in between `__enter__` and `__exit__`? If, for example, you want to create a node, add attributes, and set attributes, you'd have to call `.doIt()` thrice, right?

---

I oppose `node["attribute"]` syntax because it looks like PyMel ;) 

Really, though, adding a `__getattr__` method to the MFnDependencyNode binding sounds good - and to the MPlug binding so you could do something like: 'node['parent'][0]['child']' to get at compound/array attributes.

**Comment by Muream** [comment]
> I oppose `node["attribute"]` syntax because it looks like PyMel ;)

Wait you meant `node.attribute` right? haha

> Really, though, adding a `__getattr__` method to the MFnDependencyNode binding sounds 

And I assume you meant `__getitem__` there?

Either way, I don't have really strong opinions on this, I just find `node["attribute"]` a bit awkward to write all the time

**Comment by yantor3d** [comment]
Yes, I meant those. 

I could have sworn `node['attribute']` was a thing in PyMel...

**Comment by mottosso** [comment]
> Can DGModifier as a context handle the user calling .doIt() multiple times in between __enter__ and __exit__?

Yes! This works in the way we hope.

```py
mod.createNode("transform")
mod.doIt()
mod.createNode("transform")
mod.doIt()
mod.undoIt()  # Undo the whole modifier
```

> As for the node["attr"] thing, I like the idea of easy access of the attributes but I don't think I like the syntax.

This would be one of those opinionated decisions, but I can see what you mean.

It could also be added as a method.

```py
node.attr("translateX")
```

The thing I found convenient with dict-like access is that it turns abominations like...

```py
# This..
node.attr("translate").child(0).set(5)
node.attr("rotateX").connect(node.attr("translate").child(1))

# ..into this
node["translate"][0] = 5
node["rotateX"].connect(node["translate"][1])
```

Clean separation between what is attribute vs method. Can even use the equal sign to get rid of any "set" methods. Brrr. But yes, it is subjective.

> I could have sworn node['attribute'] was a thing in PyMel...

In PyMEL (a.k.a. The Abomination) you can't be sure whether something is an attribute or method on an object.

```py
node.rotate() # Which is it?
node.addAttribute("rotate")
node.rotate() # Did we hide the method?
```

> Really, though, adding a __getattr__ method to the MFnDependencyNode binding sounds good

That reminds me that `node["attribute"]` needs `node` to begin with. And what is that? Ideally, it would be returned from `createNode`.

```py
mod = cmdc.DGmodifier()
node = mod.createNode("transform")
mod.doIt()
node["translateX"] = 5
```

But then we're making much larger changes to the API we're wrapping.. Hmmmm.

Let's sit on it and leave this PR focused on DGModifier. It's something we can explore once everything is in place and we can actually see with our own eyes the advantages/disadvantages it would bring to the table.

**Comment by mottosso** [comment]
Actually maybe that is the answer. In addition to never returning MStatus, what if we never returned MObject? :O Instead, we'd return the equivalent object it represents, like a `DagNode`.

**Comment by Muream** [comment]
Probably worth tracking this discussion in a proper issue rather than hidden in this PR, looks like there's more to discuss there

**Comment by yantor3d** [comment]
Agreed. The initial goal of this project is feature parity with the C++ API. Making it more Pythonic and improving the UX should have a proper discussion.

**Comment by yantor3d** [comment]
Ready for review and approval.

---

I had a thought - since pybind/C++ can handle overloading functions, do we really need "newPlugValue*" methods suffixed for each data type?

**Comment by yantor3d** [comment]
I see the maya-linux 2022 checks failed ... is it possible to run the test suite in docker on a local machine?

**Comment by mottosso** [comment]
https://github.com/mottosso/cmdc/blob/6aac9c5b7109f0e88bc386aade6d8fe8b47e2c8f/src/MDGModifier.inl#L9

Let's keep in mind the poor souls who's screens and IDEs only allow 80 characters per line.

> validate::object::assert_has_fn

These are a good idea, I can see many common patterns like these appearing. But how about just `validate::has_fn`? Seems needless to have `object` along with both `assert` and `validate`.

> I had a thought - since pybind/C++ can handle overloading functions, do we really need "newPlugValue*" methods suffixed for each data type?

I see what you mean.. Ideally, we'd have `newPlugValue(my_value_of_any_type)` and call the appropriate override, and then *also* make sure that datatype actually lines up with the attribute type, such as if the attribute is an `MDistance` or `Int` etc. If the attribute and overload do not line up, that's a type error.

But I wonder it if doesn't get too complex? If anything, I think we'll need these *along* with a simplified version for one-off uses in code. I find that in the vast majority of cases, I know what type goes into an attribute and wouldn't want additional logic consuming precious CPU cycles double-checking it.

If we *only* implement the overloading and *not* check against the attribute type.. Then I think we're too far into Python duck-typing land and risk calling `newPlugValueMDistance` on an int attribute without realising it which could/would crash Maya. Those crashes would be hard to debug.

But yes, this is definitely something that could use some more finesse than what the API currently does on its own.

> I see the maya-linux 2022 checks failed ... is it possible to run the test suite in docker on a local machine?

Yes, if you have docker, you can run what CI runs here:

https://github.com/mottosso/cmdc/blob/5b9c56ae4cbaff8fda826d4a78d369d24bcb23b4/.github/workflows/main.yml#L121-L171

CI runs in the directory of the repository, so basically `cd cmdc/`, and in the Docker container specified under `matrix.image`.

```pwd
$ cd cmdc
$ docker run --name cmdc2022 -ti -v ${pwd}:/workdir mottosso/maya:2022
$$ mayapy --version  # All of Maya is here, but no build environment yet
$$ yum install centos-release-scl -y
$$ yum install devtoolset-7 bc -y
$$ ...
```

Once you've done those once, you can (should be able to) call `docker commit cmdc2022` to avoid having to build it again, and then call.

```pwd
cd cmdc
docker run -ti --rm -v ${pwd}:/workdir cmdc2022 mayapy -m nose -xv --exe ./tests
```

Although safest would be to make a new Dockerfile with the commands. Let me know if you run into issues with this.

**Comment by mottosso** [comment]
Was going to mention this as well regarding the newPlugValue, this is how I've been wrapping it in all of my code for the past few years.

https://github.com/mottosso/cmdx/blob/2ef519aeadede0db204c23cc5a6e008168e7a96d/cmdx.py#L4327-L4341

```py
...
    elif isinstance(value, om.MAngle):
        plug._mplug.setMAngle(value)


    elif isinstance(value, om.MDistance):
        plug._mplug.setMDistance(value)


    elif isinstance(value, om.MTime):
        plug._mplug.setMTime(value)


    elif isinstance(value, om.MQuaternion):
        _python_to_plug(value.asEulerRotation(), plug)


    elif isinstance(value, om.MVector):
        for index, value in enumerate(value):
            _python_to_plug(value, plug[index])
```

Come to think of it, it's rare to ever run into crashes here but that may also be because I'm careful not to pass the wrong type/attribute combination. So maybe it isn't such a bad idea doing this for cmdc too.

**Comment by mottosso** [comment]
> validate::object::assert_has_fn

I also realised we've already got a convention for validating plugs, should we not continue with that? I.e. using `assert_*`?

- https://github.com/mottosso/cmdc/blob/master/src/util/plug.hpp

**Comment by yantor3d** [comment]
| Let's keep in mind the poor souls who's screens and IDEs only allow 80 characters per line.

A hard 80 character limit is going to require a lot of line breaks, especially in the docstrings. Could we do a soft 120?

---

I'll collapse the `validate::object` namespace down to `validate` and drop the `assert` from the function names since `validate::assert_*` is redundant. In order to keep the MR focused, I'll do the same to the functions in the `plug` namespace in another branch.

--- 

For overloading the functions, I was thinking of something like this:

```
    .def("newPlugValue", [](MDGModifier & self, MPlug plug, bool value) {
        plug::assert_not_null(plug);

        MStatus status = self.newPlugValueBool(plug, value);

        CHECK_STATUS(status);
    }
```

Since as far as I can tell, pybind is strictly typed and if you pass a value for which there is not a matching `newPlugValue` overload, it will raise a TypeError.

---

Having no knowledge of Docker I'm not sure how to convert that GitHub workflow into a docker setup.

**Comment by yantor3d** [comment]
Great... I fixed a merge conflict with `master` and now all the linux tests are broken:|

**Comment by mottosso** [comment]
> A hard 80 character limit is going to require a lot of line breaks, especially in the docstrings. Could we do a soft 120?

80 where possible, no need to break our backs.

> Since as far as I can tell, pybind is strictly typed and if you pass a value for which there is not a matching newPlugValue overload, it will raise a TypeError.

Yes, true, but the issue I'm referring to is calling e.g. `newPlugValueDouble` on a e.g. boolean attribute. The modifier won't bother checking how much data actually goes into an attribute before attempting to set it. It'll happily write 4 bytes into a 2-byte variable if you ask it to.

```py
mod.newPlugValue(boolAttr, 2.0)
# Invokes newPlugValueDouble, twice the size of a bool
```

There's still value in having it though. Just not as a replacement to `newPlugValue` which is reserved for MObject. We need a new name, such as `autoPlugValue()`? Or heck, all of those names are whack. "new plug value"? It's hardly new, it's just setting an attribute. So how about `DGModifier::setAttr()`? I'll once again reference cmdx because this aspect has been solid for a few years.

- https://github.com/mottosso/cmdx/blob/2ef519aeadede0db204c23cc5a6e008168e7a96d/cmdx.py#L5238

> Having no knowledge of Docker I'm not sure how to convert that GitHub workflow into a docker setup. I managed to manually setup the docker container interactively following the steps in the workflow, but ran into a problem because I didn't know how to put the source code into the docker so it could build.

Here's something we could add to the repo to simplify that.

**Usage**

Paste the below dockerfile into `cmdc/Dockerfile.2022`, and call the below.

```bash
cd cmdc
docker build -t cmdc:2022 -f Dockerfile.2022 .  # 5-10 minutes, 2GB download, one-off
docker run -ti --rm -v ${pwd}:/workspace cmdc:2022 ./build_linux.sh 2022  # regular build, 10-20 seconds
docker run -ti --rm -v ${pwd}:/workspace cmdc:2022 mayapy -m nose -xv --exe ./tests  # regular tests 1-2 seconds
```

cmdcdocke

**Dockerfile.2022**

```dockerfile
# Build locally for Linux on any platform, e.g. Windows
FROM mottosso/maya:2022

RUN yum install centos-release-scl -y && \
    yum install devtoolset-7 bc -y

# Download devkit
ENV DEVKIT_LOCATION=/root/devkitBase
ENV DEVKIT "https://autodesk-adn-transfer.s3.us-west-2.amazonaws.com/ADN%20Extranet/M%26E/Maya/devkit%202022/Autodesk_Maya_2022_DEVKIT_Linux.tgz"
RUN wget $DEVKIT -O "/root/devkit.tgz" && \
    tar -xvf /root/devkit.tgz $pwd

# Setup Test Environment
RUN mayapy -m pip install --user \
        nose==1.3.7 \
        nose-exclude==0.5.0 \
        coverage==5.5 \
        flaky==3.7.0 \
        six==1.16.0 \
        sphinx==1.8.5 \
        sphinxcontrib-napoleon==0.7

# Since 2019, this sucker throws an
# unnecessary warning if not declared.
RUN mkdir -p /var/tmp/runtime-root
ENV XDG_RUNTIME_DIR /var/tmp/runtime-root
ENV MAYA_DISABLE_ADP 1

# The local /build directory
ENV PYTHONPATH=/workspace/build

WORKDIR /workspace

COPY docker_entrypoint.sh /usr/bin/entrypoint.sh
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT [ "/usr/bin/entrypoint.sh" ]
```

**Comment by mottosso** [comment]
> Great... I fixed a merge conflict with master and now all the linux tests are broken:|

Weird, I'm looking, but I can't see where this happens. It appears to be saying there are two DagPath's being defined? :O

**Comment by yantor3d** [comment]
> Weird, I'm looking, but I can't see where this happens. It appears to be saying there are two DagPath's being defined? :O

It looks like MDagPath.inl is included in `main.cpp` twice ... probably from when I merged master

**Comment by Muream** [comment]
Regarding line length, I've grown fond of 88. That's the default in the black formatter and it's a pretty good compromise. You can still open multiple files side by side without clipping the text and it's a lot less restraining than 80.

I've gotten somewhat comfortable with docker last week, a few things that helped me:
Each `RUN` command in a dockerfile runs in its own shell. This means lines like `. scl_source enable devtoolset-7 || true` which makes g++ available in the current shell would need to be part of all the `RUN` commands that need g++ available.
I'm guessing that's the reason why it's included in the `entry_point.sh` instead.
With that configuration, if you want to open an interactive terminal you can pass `bash` instead of `./build_linux.sh 2022` like so `docker run -ti --rm -v ${pwd}:/workspace cmdc:2022 bash`. I found that pretty useful to figure things out.

> Weird, I'm looking, but I can't see where this happens. It appears to be saying there are two DagPath's being defined? :O
If that comes from something I've done when implementing DagPath, let me know.

**Comment by yantor3d** [comment]
Thanks for the Dockerfile - I've added it to the repo and got the tests to pass for linux locally. 

If we include a Dockerfile for each version of Maya, are we going to need to put the devkits in version specific folders?

**Comment by yantor3d** [comment]
All builds passed, ready for review/approval

Again, please squash the commits when you merge :)

**Comment by mottosso** [comment]
> It looks like MDagPath.inl is included in main.cpp twice ... probably from when I merged master

Aah, yes that would make sense. I had to move lines around to have things defined before they were used in the MDagModifier.

> Regarding line length, I've grown fond of 88.

Haha, everyone has a favourite. :) Let's stick to 80.

> I'm guessing that's the reason why it's included in the entry_point.sh instead.

Correct! I would have put it in the startup script for bash, `~/.bashrc` but for whatever reason this GCC thingy doesn't like that, so it had to be a separate script..

> I found that pretty useful to figure things out.

For sure, and just to demystify those arguments.

```bash
docker run            # The sub-command to run a container, another one being build. See docker -h for all
-ti                   # Run in interactive mode, basically a REPL or interactive interpreter
--rm                  # Delete the container when you exit. If you don't, you can delete them via `docker rm` and list them with `docker ps`
-v ${pwd}:/workspace  # Map a local directory to a directory in the container, e.g. -v "c:\my\dir":/his/dir
cmdc:2022             # Name of the container
bash                  # Finally, one or more commands to run once you enter the container
```

That's pretty much all you need for most things. One more being `-p` which lets you map a port on `localhost` to a port in the container. Useful for running a web service or the like in a container.

> If we include a Dockerfile for each version of Maya, are we going to need to put the devkits in version specific folders?

I contemplated making the Dockerfile independent of the devkit, but since it's based on a specific version of Maya it's only really suited for one devkit. So the devkit is downloaded into the container itself and won't need to be downloaded locally.

If we are to use this dockerfile, we'll need to duplicate it for each Maya, swap out the top-level `FROM` statement  and update the devkit download path. CI didn't need this, since it's re-building the container every time. For testing locally, it's unlikely we'll need all versions of Maya all the time either, so there isn't much to gain from making all of these Dockerfiles.

I'd suggest we keep this one Dockerfile for local testing, and as a template for how to test with other versions of Maya too when needed, and leave CI as-is. At least until it becomes an a problem.

> Again, please squash the commits when you merge :)

I'd really rather not to be honest. :S When we browse the code later, I often find myself looking for the commit associated with it. If that commit is *huuuge* (like a squased PR) then it becomes almost impossible to gather any useful information from it. Commits should be small, with a descriptive message, such that the lines coming out of it have context.

Can we not squash? Also, what is the reason you'd like to squash?

**Comment by yantor3d** [comment]
> Can we not squash? Also, what is the reason you'd like to squash?

It's your repo, so it's your call. I'm used to squashing at work because it (in theory) means the commits to `main` are clear like "Fix X (ticket)" or "Add feature Y (ticket)" without all the noise of commits.

Or maybe I just need to get better at doing clean commits? 🙃

**Comment by mottosso** [comment]
This PR is the "Fix X" and "Add feature Y", all commits are WIP. :)

Whenever you land on any one of the contained commits, this PR is what shows up as their "parent" or "group". What they do is provide additional context within the group, and whenever you dive into history you can never have too much context behind where lines came from and what thought processes went into them.

Great work, let's keep it going! :D

**Pull request merged**
