### PR TITLE
MObject: implement missing functions and add tests

### PR DESCRIPTION
**Pull request by Muream**
I have very little experience with C++ or writing bindings so I figured I would start small.
If the PR suits you, I'll start working on other classes.

I did the following:
- Implemented `MObject.__eq__`.
- Changed `MObject.__repr__` to include the apiTypeStr (wasn't 100% sure about the best way to format the string there).
- Added tests for all the `MObject` methods.

### CODE REVIEW

**Comment by mottosso** [comment]
Hey @Muream, this looks solid.

For operators like equality, there's a pybind11 shorthand that looks [like this](https://github.com/mottosso/cmdc/blob/4f0b3fbc13832e6e7f25d73981bec10820f2c360/src/Math.inl#L91). I'm not sure it'll work for MObject, but it would be worth a shot to keep it consistent with other operators. Could you give it a try?

**Comment by Muream** [comment]
@mottosso Worked like a charm 👍

**Comment by mottosso** [comment]
Sweet :) It makes it trivial to add all of the natively supported operators as one-liners. It's very nice.

That does it, builds are succeeding on all platforms and all versions Maya, one step closer to a better Python API. Nice work @Muream and welcome aboard. :D

**Comment by Muream** [comment]
Thanks!
Excited to see this become a thing :)

**Pull request merged**
