### PR TITLE
Implment MDagModifier bindings

### PR DESCRIPTION
**Pull request by yantor3d**
### Added
 - Implement `MDagModifier` bindings

### Fixes
 - Fix typo in `build_win32.ps1` so MFn.Types.inl is cleaned up after each build

### CODE REVIEW

**Comment by yantor3d** [comment]
I thought implementing MDagModifier was going to be a piece of cake, but I immediately ran into a problem.

MDagModifier is a subclass of MDGModifier. However, I can't figure out how to subclass an existing binding. The official docs don't seem to say, and this [issue](https://github.com/pybind/pybind11/issues/1193) suggests a way that feels kind of hacky...

**Comment by yantor3d** [comment]
After a lot of googling I have concluding that none of the examples out there work when using `.inl` files. 

I did eventually figure out a solution that works - wrapping the base class in an `ifndef/define/endif` preprocessor and including it before the subclass definition. However, I but I don't know if this solution will work for classes with multiple subclasses. We'll burn that bridge when we get to it.

**Comment by Muream** [comment]
@yantor3d quick heads up, I've changed the format of the docstrings in my last PR that's now been merged, you may get conflicts there

We now also have automatically generated stubs, if that step fails during CI, make sure that:
1. The docstrings in your `.inl` files don't contain any signatures
2. that your classes have been declared in `ForwardDeclaration.inl` before they're used in any signatures. Those classes don't necessarily need any implementation, they just need to be declared for pybind to be able to map the C++ type to the Python type.

A few other things might trip you so if you run into any problem, give me a ping.

I'll add those notes in the `contributing.md` as well during the weekend

**Comment by mottosso** [comment]
Great work @Muream. Would it be possible to add a note to the README as well, along with a short gif demonstrating the final result in any of the editors you are using it in?

**Comment by Muream** [comment]
Yep I can absolutely do that

**Comment by yantor3d** [comment]
Thanks for the heads up! I'll take care of the merge after work.

**Comment by yantor3d** [comment]
Stabalized and ready for merge

**Pull request merged**
