### PR TITLE
Improve stubs part two

### PR DESCRIPTION
**Pull request by Muream**
So, when trying to record the gif for the readme, I realized the completion wasn't working on some classes like `SelectionList`.
Turns out pybind11-stubgen gets a bit confused when a class has an inner class defined and tries to import the parent class as a module. This is tracked by this issue: https://github.com/sizmailov/pybind11-stubgen/issues/36

I've opted to just remove the unwanted imports once the stubs are generated, might be a bit brute force but that felt like the only option that didn't cause other issues somewhere else in the stubs.

I'll also update the readme and contributing.md as part of this PR.
@mottosso is there a good place where I can store the gif?

### CODE REVIEW

**Comment by mottosso** [comment]
> So, when trying to record the gif for the readme, I realized the completion wasn't working on some classes like SelectionList

My favourite part of making gifs. :) It's the ultimate unit test.

> is there a good place where I can store the gif?

Yep, just drag and drop it into any issue, even here. It'll generate a universally unique link that never expires and can be used anywhere. If your gif is larger than 10 mb it won't work, but your gif should *not* be more than 10 mb.

Actually, make it an MP4 if you can, it'll be smaller and more crisp. Still try keep it under 10 seconds though, else split it up into multiple gifs that show off one small feature at a time.

**Comment by Muream** [comment]
Uploading some videos for the readme

Auto-completion

https://user-images.githubusercontent.com/3117205/121938610-50b24100-cd4c-11eb-9325-28c35e00f4d7.mp4


Type checking in action

https://user-images.githubusercontent.com/3117205/121938616-53ad3180-cd4c-11eb-9b5d-d2f7e7829b82.mp4

**Comment by Muream** [comment]
Ah, looks like the `<video>` tag doesn't work with markdown on GitHub :(

@mottosso do you prefer the videos to display like in my previous comment (collapsable and with playback controls) or more like gifs (no controls, with autoplay and looping)?

**Comment by mottosso** [comment]
Hmm.

image

I don't mind non-looping mp4. So long as a gif isn't too large, ideally 2-3 mb, then either is OK I think. Up to you.

**Comment by Muream** [comment]
Hah, plays fine on chrome but not firefox,
I think I prefer looping gifs for short examples like this, looks cleaner with the rest of the file

**Comment by Muream** [comment]
All ready to go if that works for you 👍

**Comment by mottosso** [comment]
Looks good to me! I made the gifs a bit smaller to make it fit in a little better with the surrounding text.

**Pull request merged**
